[package]
name = "tc39-test262"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true, features = ["derive"] }
phf = { workspace = true, features = ["macros"] }
clap = { workspace = true, features = ["derive"] }
bitflags.workspace = true
once_cell.workspace = true
regex.workspace = true
serde_repr = "^0.1.18"
color-eyre = "0.6.2"
rustc-hash = "1.1.0"
serde_yaml = "0.9.32"

[lints]
workspace = true
